### ISSUE TITLE
is this compatible with remarkable 2 

### ISSUE THREAD

**Issue by teto** [pl-semiotics/nix-remarkable#4]
just received the remarkable tablet 2 and looking into what I can do with it and nixos. Any link welcome.

**Comment by jonahweissman** [comment]
In case you haven't seen it yet, a remarkable 2 platform for cross-compilation has been added to nixpkgs. See more here: https://discourse.nixos.org/t/done-remarkable1-cross-compile-toolchain-for-nix/9961/17

Here's a guide for installing nix on armv7l devices: https://github.com/DavHau/nix-on-armv7l
(worked for me on remarkable 2)

**Comment by pl-semiotics** [comment]
There's no RM2 support in here yet, but there will be shortly (I'm ironing out some kinks with it right now). I'll also post on the Discourse thread ~soon clarifying the relationship between this overlay and the platform upstream---long story short, this is tuned for producing easy-to-distribute (mostly static, link against the libc present on the device) binaries that are fully ABI compatible with the device, unlike the upstream support which is based around the open-source toolchain and tends to assume that you have a Nix store on the device.

**Comment by teto** [comment]
thanks for the intel, will try to play a bit with it

**Comment by pl-semiotics** [comment]
@teto reMarkable 2 support is here now.

**Comment by teto** [comment]
fantastic thank you !
